/******************************************************************/
// Clase PlayerView
//
// (C) Antonio Calderón Cortiñas
// (C) Francisco Rafael Checa Molina
// (C) Juan Pablo Porcel Porcel
/******************************************************************/


package GUI;

import java.awt.*;
import java.util.ArrayList;
import javax.swing.JPanel;
import napakalaki.BadStuff;
import napakalaki.CultistPlayer;
import napakalaki.Napakalaki;
import napakalaki.Player;
import napakalaki.Treasure;


public class PlayerView extends javax.swing.JPanel {

    
    private Player playerModel;
    private BadStuff bsModel;
    
    private Napakalaki napakalakiModel;
    
    
    public void setNapakalaki(Napakalaki n)
    {
	this.napakalakiModel = n;
    }
    
    public ArrayList<Treasure> getSelectedTreasures(JPanel aPanel) {
	// Se recorren los tesoros que contiene el panel,
	// almacenando en un vector aquellos que están seleccionados.
	// Finalmente se devuelve dicho vector.
	TreasureView tv;
	ArrayList<Treasure> output = new ArrayList();
	for (Component c :aPanel.getComponents())
	{
	    tv = (TreasureView) c;
	    if ( tv.isSelected() )
		output.add ( tv.getTreasure() );
	}
	return output;
    }

    
    /**
     * Creates new form PlayerView
     */
    public PlayerView() {
	initComponents();
	this.levelBar.setMaximum(10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        visibleTreasures = new javax.swing.JPanel();
        hiddenTreasures = new javax.swing.JPanel();
        aname = new javax.swing.JLabel();
        buy = new javax.swing.JButton();
        make = new javax.swing.JButton();
        discard = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        clevel = new javax.swing.JLabel();
        pBS = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nOcultos = new javax.swing.JLabel();
        tOcultos = new javax.swing.JLabel();
        nVisibles = new javax.swing.JLabel();
        tVisibles = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        nCultists = new javax.swing.JLabel();
        cultistView = new GUI.CultistView();
        die = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        levelBar = new javax.swing.JProgressBar();
        regalar = new javax.swing.JButton();
        gracias = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Player", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), java.awt.Color.black)); // NOI18N

        jLabel1.setText("Name");

        jLabel2.setText("Level Basic");

        visibleTreasures.setBackground(javax.swing.UIManager.getDefaults().getColor("Nb.ScrollPane.Border.color"));
        visibleTreasures.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Visible Treasures"));

        hiddenTreasures.setBackground(javax.swing.UIManager.getDefaults().getColor("Nb.ScrollPane.Border.color"));
        hiddenTreasures.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Hidden Treasures"));

        aname.setFont(new java.awt.Font("URW Bookman L", 1, 15)); // NOI18N
        aname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aname.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buy.setFont(new java.awt.Font("L M Mono Caps10", 1, 15)); // NOI18N
        buy.setText("Buy Levels");
        buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyActionPerformed(evt);
            }
        });

        make.setFont(new java.awt.Font("L M Mono Caps10", 1, 15)); // NOI18N
        make.setText("Make Visible");
        make.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeActionPerformed(evt);
            }
        });

        discard.setFont(new java.awt.Font("L M Mono Caps10", 1, 15)); // NOI18N
        discard.setText("Discard Treasures");
        discard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardActionPerformed(evt);
            }
        });

        jLabel8.setText("Combat Level");

        clevel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        clevel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clevel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pBS.setBackground(javax.swing.UIManager.getDefaults().getColor("Slider.shadow"));
        pBS.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pending BadStuff", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), java.awt.Color.black)); // NOI18N

        jLabel3.setText("Number hidden to lose:");

        jLabel4.setText("Type:");

        jLabel5.setText("Number visible to lose:");

        jLabel6.setText("Type:");

        javax.swing.GroupLayout pBSLayout = new javax.swing.GroupLayout(pBS);
        pBS.setLayout(pBSLayout);
        pBSLayout.setHorizontalGroup(
            pBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBSLayout.createSequentialGroup()
                .addGroup(pBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pBSLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(nOcultos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pBSLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(tOcultos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
            .addGroup(pBSLayout.createSequentialGroup()
                .addGroup(pBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pBSLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nVisibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pBSLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tVisibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pBSLayout.setVerticalGroup(
            pBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBSLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(nOcultos, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tOcultos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nVisibles, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tVisibles, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jLabel7.setText("Nº cultists:");

        nCultists.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        nCultists.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nCultists.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cultistView.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Character"));

        die.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        die.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Die");

        regalar.setText("Regalar");
        regalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regalarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(visibleTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hiddenTreasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buy)
                                .addGap(60, 60, 60)
                                .addComponent(make)
                                .addGap(57, 57, 57)
                                .addComponent(discard))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aname, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(jLabel1)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(levelBar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel2)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(5, 5, 5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(clevel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(die, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(nCultists, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cultistView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(pBS, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(regalar)
                                .addGap(29, 29, 29)
                                .addComponent(gracias, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(die, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(levelBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(visibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(make)
                    .addComponent(buy)
                    .addComponent(discard)
                    .addComponent(regalar)
                    .addComponent(gracias, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cultistView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nCultists, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void makeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeActionPerformed
        // TODO add your handling code here:
	ArrayList<Treasure> selHidden = getSelectedTreasures (hiddenTreasures);
	
	napakalakiModel.makeTreasuresVisible (selHidden);

	setPlayer (napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_makeActionPerformed

    
    private void discardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardActionPerformed
        // TODO add your handling code here:
	ArrayList<Treasure> selHDiscard = getSelectedTreasures (hiddenTreasures);
	ArrayList<Treasure> selVDiscard = getSelectedTreasures (visibleTreasures);
	
	
	napakalakiModel.discardHiddenTreasures(selHDiscard);
	napakalakiModel.discardVisibleTreasures(selVDiscard);

	setPlayer (napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_discardActionPerformed

    private void buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyActionPerformed
        // TODO add your handling code here:
	ArrayList<Treasure> selHBuy = getSelectedTreasures (hiddenTreasures);
	ArrayList<Treasure> selVBuy = getSelectedTreasures (visibleTreasures);
	
	
	napakalakiModel.buyLevels(selVBuy, selHBuy);

	setPlayer (napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_buyActionPerformed

    private void regalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regalarActionPerformed
        // TODO add your handling code here:
	this.regalarTesoro();
    }//GEN-LAST:event_regalarActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aname;
    private javax.swing.JButton buy;
    private javax.swing.JLabel clevel;
    private GUI.CultistView cultistView;
    private javax.swing.JLabel die;
    private javax.swing.JButton discard;
    private javax.swing.JLabel gracias;
    private javax.swing.JPanel hiddenTreasures;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JProgressBar levelBar;
    private javax.swing.JButton make;
    private javax.swing.JLabel nCultists;
    private javax.swing.JLabel nOcultos;
    private javax.swing.JLabel nVisibles;
    private javax.swing.JPanel pBS;
    private javax.swing.JButton regalar;
    private javax.swing.JLabel tOcultos;
    private javax.swing.JLabel tVisibles;
    private javax.swing.JPanel visibleTreasures;
    // End of variables declaration//GEN-END:variables

    
    
    public void fillTreasurePanel (JPanel aPanel, ArrayList<Treasure> aList) {
	// Se elimina la información antigua
	aPanel.removeAll();
	// Se recorre la lista de tesoros construyendo y añadiendo sus vistas
	// al panel
	for (Treasure t : aList) {
	    TreasureView aTreasureView = new TreasureView();
	    aTreasureView.setTreasure (t);
	    aTreasureView.setVisible (true);
	    aPanel.add (aTreasureView);
	}
	// Se fuerza la actualización visual del panel
	aPanel.repaint();
	aPanel.revalidate();
    }
    
    // Actualiza la info del jugador
    public void setPlayer (Player p) {
	playerModel = p;
	bsModel = playerModel.getPendingBadStuff();
	// Incluir instrucciones para actualizar su nombre, nivel, etc.
	this.aname.setText(playerModel.getName());
	this.clevel.setText(Integer.toString(playerModel.getCombatLevel()));
	this.nCultists.setText(Integer.toString(CultistPlayer.getTotalCultistPlayers()));
	if(this.playerModel.isDead())
	    this.die.setText("Yep");
	else
	    this.die.setText("Nope");
	
	/******************** pending bad stuff ******************/
	
	if (this.bsModel != null)
	{	
	    this.nOcultos.setText(Integer.toString(bsModel.getnHiddenTreasures()));
	    this.tOcultos.setText(bsModel.getSpecificHiddenTreasures().toString());

	    this.nVisibles.setText(Integer.toString(bsModel.getnVisibleTreasures()));
	    this.tVisibles.setText(bsModel.getSpecificVisibleTreasures().toString());
	}
	
	// Incluir también la orden para actualizar la vista asociada a su carta
	// de sectario (si es el caso) mediante el método setCultist
    	if(this.playerModel.getClass().getSimpleName().equals("CultistPlayer"))
	    this.cultistView.setCultist(((CultistPlayer) playerModel).getCultistCard());
	else
	{
	    this.cultistView.setCultist(null);
	    this.setCharacter(this.playerModel.getCharacter());
	}
	
	
	
	this.levelBar.setValue(this.playerModel.getLevels());
	this.levelBar.setString(Integer.toString(this.playerModel.getLevels()));
	this.levelBar.setStringPainted(true);	
	
	
	this.regalar.setEnabled(puede);
	if (puede)
	    this.gracias.setText("");
	
	
	// A continuación se actualizan sus tesoros
	fillTreasurePanel (visibleTreasures, playerModel.getVisibleTreasures());
	fillTreasurePanel (hiddenTreasures, playerModel.getHiddenTreasures());
	repaint();
	revalidate();
    }
    
    public void setCharacter(String c)
    {
	String icon = "/res/players/" + c + ".jpg";
	this.cultistView.setCharacter(icon, this.playerModel.getName());
    }
    
    
    
    // EXAMEN
    
    
    // Botón regalar
    
    
    Boolean puede = true;
    
    
    public void regalarTesoro()
    {
	ArrayList<Treasure> selHBuy = getSelectedTreasures (hiddenTreasures);
	
	
	gracias.setText(napakalakiModel.regalarTesoro(selHBuy));
	
	this.regalar.setEnabled(false);
	puede = false;
	
	setPlayer(napakalakiModel.getCurrentPlayer());	
    }
    
    
    public void puedeRegalar  (Boolean b)
    {
	puede = b;
    }
    
    // En setPlayer se habilita el boton regalar segun la variable puede
    
    // FIN EXAMEN


}
