/******************************************************************/
// Clase PlayerNamesCapture
//
// (C) Antonio Calderón Cortiñas
// (C) Francisco Rafael Checa Molina
// (C) Juan Pablo Porcel Porcel
/******************************************************************/


package GUI;

import java.awt.*;
import java.util.ArrayList;


public class PlayerNamesCapture extends javax.swing.JDialog {
    
    
    
    private ArrayList<String> names = new ArrayList<String>();
    private ArrayList<String> characters = new ArrayList<String>();

    public PlayerNamesCapture(java.awt.Frame parent, boolean modal) {
	super(parent, modal);
	
	initComponents();
	this.setLocationRelativeTo(null);
	
	this.addWindowListener(new java.awt.event.WindowAdapter() {
	    @Override
	    public void windowClosing(java.awt.event.WindowEvent e) {
		System.exit(0);
	    }		
	});
	
	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        player1 = new javax.swing.JLabel();
        player2 = new javax.swing.JLabel();
        player3 = new javax.swing.JLabel();
        namep1 = new javax.swing.JTextField();
        namep2 = new javax.swing.JTextField();
        namep3 = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        play = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        character1 = new javax.swing.JComboBox();
        character2 = new javax.swing.JComboBox();
        character3 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        player1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        player1.setText("Player 1");

        player2.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        player2.setText("Player 2");

        player3.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        player3.setText("Player 3");

        cancel.setFont(new java.awt.Font("L M Mono Caps10", 1, 15)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        play.setFont(new java.awt.Font("L M Mono Caps10", 1, 15)); // NOI18N
        play.setText("Play");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel1.setText("Enter the names of the players:");

        character1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arquera", "Bardo", "Elfo", "Guerrero", "Mago", "Orco" }));
        character1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                character1ActionPerformed(evt);
            }
        });

        character2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arquera", "Bardo", "Elfo", "Guerrero", "Mago", "Orco" }));
        character2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                character2ActionPerformed(evt);
            }
        });

        character3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arquera", "Bardo", "Elfo", "Guerrero", "Mago", "Orco" }));
        character3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                character3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancel)
                .addGap(18, 18, 18)
                .addComponent(play)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(player1)
                            .addComponent(player2)
                            .addComponent(player3))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namep1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(namep2)
                            .addComponent(namep3))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(character1, 0, 218, Short.MAX_VALUE)
                            .addComponent(character2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(character3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1)
                    .addComponent(namep1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(character1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player2)
                    .addComponent(namep2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(character2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(player3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(namep3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(character3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(play))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
	System.exit(0);
    }//GEN-LAST:event_cancelActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        
	names.add(namep1.getText());
	names.add(namep2.getText());
	names.add(namep3.getText());
	
	characters.add(this.character1.getSelectedItem().toString());
	characters.add(this.character2.getSelectedItem().toString());
	characters.add(this.character3.getSelectedItem().toString());
	this.dispose();
	
    }//GEN-LAST:event_playActionPerformed

    private void character2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_character2ActionPerformed
        // TODO add your handling code here:
	
	
    }//GEN-LAST:event_character2ActionPerformed

    private void character1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_character1ActionPerformed
        // TODO add your handling code here:
	
    }//GEN-LAST:event_character1ActionPerformed

    private void character3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_character3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_character3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public ArrayList<String> getNames() {
	this.setVisible(true);
	return names;
    }
    
    
    public ArrayList<String> getCharacters() {
	return characters;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JComboBox character1;
    private javax.swing.JComboBox character2;
    private javax.swing.JComboBox character3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField namep1;
    private javax.swing.JTextField namep2;
    private javax.swing.JTextField namep3;
    private javax.swing.JButton play;
    private javax.swing.JLabel player1;
    private javax.swing.JLabel player2;
    private javax.swing.JLabel player3;
    // End of variables declaration//GEN-END:variables
}
